# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import taskflow_pb2 as taskflow__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in taskflow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskFlowStub:
    """----- Service -----

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/taskflow.TaskFlow/CreateTask',
                request_serializer=taskflow__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=taskflow__pb2.CreateTaskResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/taskflow.TaskFlow/GetTask',
                request_serializer=taskflow__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=taskflow__pb2.Task.FromString,
                _registered_method=True)
        self.UpdateStatus = channel.unary_unary(
                '/taskflow.TaskFlow/UpdateStatus',
                request_serializer=taskflow__pb2.UpdateStatusRequest.SerializeToString,
                response_deserializer=taskflow__pb2.Task.FromString,
                _registered_method=True)
        self.AssignTask = channel.unary_unary(
                '/taskflow.TaskFlow/AssignTask',
                request_serializer=taskflow__pb2.AssignTaskRequest.SerializeToString,
                response_deserializer=taskflow__pb2.Task.FromString,
                _registered_method=True)
        self.AddComment = channel.unary_unary(
                '/taskflow.TaskFlow/AddComment',
                request_serializer=taskflow__pb2.AddCommentRequest.SerializeToString,
                response_deserializer=taskflow__pb2.Task.FromString,
                _registered_method=True)
        self.DeleteTask = channel.unary_unary(
                '/taskflow.TaskFlow/DeleteTask',
                request_serializer=taskflow__pb2.DeleteTaskRequest.SerializeToString,
                response_deserializer=taskflow__pb2.Empty.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_stream(
                '/taskflow.TaskFlow/ListTasks',
                request_serializer=taskflow__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=taskflow__pb2.Task.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/taskflow.TaskFlow/Subscribe',
                request_serializer=taskflow__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=taskflow__pb2.TaskEvent.FromString,
                _registered_method=True)
        self.SearchKeywords = channel.stream_unary(
                '/taskflow.TaskFlow/SearchKeywords',
                request_serializer=taskflow__pb2.SearchEntry.SerializeToString,
                response_deserializer=taskflow__pb2.SearchSummary.FromString,
                _registered_method=True)


class TaskFlowServicer:
    """----- Service -----

    """

    def CreateTask(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Server streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchKeywords(self, request_iterator, context):
        """Client streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskFlowServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=taskflow__pb2.CreateTaskRequest.FromString,
                    response_serializer=taskflow__pb2.CreateTaskResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=taskflow__pb2.GetTaskRequest.FromString,
                    response_serializer=taskflow__pb2.Task.SerializeToString,
            ),
            'UpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatus,
                    request_deserializer=taskflow__pb2.UpdateStatusRequest.FromString,
                    response_serializer=taskflow__pb2.Task.SerializeToString,
            ),
            'AssignTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignTask,
                    request_deserializer=taskflow__pb2.AssignTaskRequest.FromString,
                    response_serializer=taskflow__pb2.Task.SerializeToString,
            ),
            'AddComment': grpc.unary_unary_rpc_method_handler(
                    servicer.AddComment,
                    request_deserializer=taskflow__pb2.AddCommentRequest.FromString,
                    response_serializer=taskflow__pb2.Task.SerializeToString,
            ),
            'DeleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTask,
                    request_deserializer=taskflow__pb2.DeleteTaskRequest.FromString,
                    response_serializer=taskflow__pb2.Empty.SerializeToString,
            ),
            'ListTasks': grpc.unary_stream_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=taskflow__pb2.ListTasksRequest.FromString,
                    response_serializer=taskflow__pb2.Task.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=taskflow__pb2.SubscribeRequest.FromString,
                    response_serializer=taskflow__pb2.TaskEvent.SerializeToString,
            ),
            'SearchKeywords': grpc.stream_unary_rpc_method_handler(
                    servicer.SearchKeywords,
                    request_deserializer=taskflow__pb2.SearchEntry.FromString,
                    response_serializer=taskflow__pb2.SearchSummary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskflow.TaskFlow', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskflow.TaskFlow', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskFlow:
    """----- Service -----

    """

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskflow.TaskFlow/CreateTask',
            taskflow__pb2.CreateTaskRequest.SerializeToString,
            taskflow__pb2.CreateTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskflow.TaskFlow/GetTask',
            taskflow__pb2.GetTaskRequest.SerializeToString,
            taskflow__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskflow.TaskFlow/UpdateStatus',
            taskflow__pb2.UpdateStatusRequest.SerializeToString,
            taskflow__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskflow.TaskFlow/AssignTask',
            taskflow__pb2.AssignTaskRequest.SerializeToString,
            taskflow__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskflow.TaskFlow/AddComment',
            taskflow__pb2.AddCommentRequest.SerializeToString,
            taskflow__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskflow.TaskFlow/DeleteTask',
            taskflow__pb2.DeleteTaskRequest.SerializeToString,
            taskflow__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/taskflow.TaskFlow/ListTasks',
            taskflow__pb2.ListTasksRequest.SerializeToString,
            taskflow__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/taskflow.TaskFlow/Subscribe',
            taskflow__pb2.SubscribeRequest.SerializeToString,
            taskflow__pb2.TaskEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchKeywords(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/taskflow.TaskFlow/SearchKeywords',
            taskflow__pb2.SearchEntry.SerializeToString,
            taskflow__pb2.SearchSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
